### ISSUE TITLE
Useless Code :\\

### ISSUE THREAD

**Issue by Jitender-Kumar-Yadav** [Deepanshu-Rohilla/Password-Genarator#1]
Nice but very basic and common code.

**Comment by Deepanshu-Rohilla** [comment]
Sir
This code is used by Crown Price of England, Donald Trump and even Robert Vadra to save their treasure. This is not for `common public`. The password generated is not supposed to be "remembered". So, it has to be of length greater than 93. 
Also, common passwords like the one for Instagram is rarely of length ≥ 93. 
So, please increase the scope of your brain and think of something huge and of diplomatic importance. As of now, it is beyond your understanding
